from app.commands.basic_commands import BasicCommands
from app.commands.web_commands import WebCommands


class CommandDispatcher:
    """Routes user commands to the appropriate command handler."""

    def __init__(self):
        self.basic_commands = BasicCommands()
        self.web_commands = WebCommands()

    def dispatch(self, text: str) -> str:
        """
        Find the appropriate command handler.

        Args:
            text: Recognized speech from the user.

        Returns:
            Response generated by the appropriate handler.
        """

        if not text:
            return (
                "Sorry, I didn't hear anything. "
                "Please try again."
            )

        # Try basic commands first.
        response = self.basic_commands.handle(text)

        if response:
            return response

        # Try web commands next.
        response = self.web_commands.handle(text)

        if response:
            return response

        # Nothing recognized.
        return (
            "Sorry, I don't understand that command yet. "
            "Please try again."
        )